name: Build

on: [push,workflow_dispatch]

jobs:
  build:
    uses: RaphaelIT7/gmodcommon-module-base/.github/workflows/compile.yml@workflow
    with:
      PROJECT_NAME: "icvar"
      BUILD_64x: "true"
      REALM: "sv"
      FINAL_REALM: "sv"
